### PR TITLE
Update gitlab-runner-version to 16.8.0 from 16.6.1

### PR DESCRIPTION
**Pull request by zosopentoolsmain**

### CODE REVIEW

**Comment by v1gnesh** [comment]
Don't merge yet, I'll push the build_and_test workflow to the remaining repos soon.
Then, we can use that to run the tests and see if it builds.

**Comment by v1gnesh** [comment]
Need to pull the latest commits from main into this branch and run the tests again..

**Comment by IgorTodorovskiIBM** [comment]
Can we rebase this one to pick up the latest updates from main?

**Comment by v1gnesh** [comment]
I think this is ready now, since https://github.com/ZOSOpenTools/gitlab-runnerport/pull/4 is merged...?

**Comment by jlee3227** [comment]
any objections to merging this and then #5 ?

**Comment by v1gnesh** [comment]
The main branch now already has `build_and_test.yml` and the update to `$PWD` in `buildenv`, from https://github.com/ZOSOpenTools/gitlab-runnerport/pull/4.

We can close this I think.

**Comment by v1gnesh** [comment]
@jlee3227 when possible, please delete this branch to clean up :)

**Pull request closed without merging**
